In [1]:
import numpy as np
from forecast_kit import ForecastKit

In [2]:
def myf(paramList):
    x = paramList[0]
    y = paramList[1]
    obs1 = x + y
    obs2 = x * x + 2 * y * y
    obsList = np.array([obs1,obs2])
    return obsList

In [3]:
observables = myf
fiducial_values = [1, 2]
covmat = np.array([[1,0],[0,1]])

In [4]:
forecaster = ForecastKit(observables, fiducial_values, covmat)

In [5]:
first_order_derivs = forecaster.get_derivatives(derivative_order = 1)
print(first_order_derivs)

[[1. 2.]
 [1. 8.]]


In [6]:
second_order_derivs = forecaster.get_derivatives(derivative_order = 2)
print(second_order_derivs)

[[[-2.20178468e-10  2.00000000e+00]
  [ 9.51801750e-14 -1.66706105e-13]]

 [[ 6.64571636e-14  1.71211676e-13]
  [-1.83482057e-11  4.00000000e+00]]]


In [7]:
fisher_matrix = forecaster.get_forecast_tensors()
print('Fisher matrix: ')
print(fisher_matrix.ndim)
print(fisher_matrix)

Fisher matrix: 
2
[[ 5.862025 20.4481  ]
 [20.4481   78.7924  ]]


In [8]:
DALI_G, DALI_H = forecaster.get_forecast_tensors(forecast_order = 2)
print('G tensor: ')
print(DALI_G.ndim)
print(DALI_G)
print('H tensor: ')
print(DALI_H.ndim)
print(DALI_H)

G tensor: 
3
[[[4.63050000e+00 1.85220000e+01]
  [2.56711914e-13 1.23466709e-12]]

 [[1.26917413e-13 6.27630464e-13]
  [9.26100000e+00 3.70440000e+01]]]
H tensor: 
4
[[[[4.00000000e+00 2.81598151e-13]
   [1.44178253e-13 8.00000000e+00]]

  [[2.81598151e-13 2.46231483e-26]
   [1.29201033e-26 5.63196302e-13]]]


 [[[1.44178253e-13 1.29201033e-26]
   [6.79579734e-27 2.88356506e-13]]

  [[8.00000000e+00 5.63196302e-13]
   [2.88356506e-13 1.60000000e+01]]]]
