# Fisher and DALI demo

This demo illustrates how to use the helper tools in <code>forecast_kit</code> to facilitate scientific forecasting.

The forecasting tools can return a Fisher matrix, and the 3-dimensional and 4-dimensional tensors of the doublet-DALI approximation.

The required inputs are:
- **A function defining your observable(s):** This should take as input a single list of parameter values, corresponding to your model parameters. It should return a list of observables. A one-parameter model, or a single observable, should still be structured as a list containing one item.
- **The fiducial values of your model parameter(s):** This should likewise be a single list of parameter values. The ordering of the parameters should match the input of your observable function.
- **The covariance matrix of the observable(s):** The ordering of the entries in the covariance matrix should match the output of your observable function.

In [1]:
import numpy as np
from derivkit.forecast_kit import ForecastKit

In [2]:
# Define a function: it returns two observables as a function of two model parameters.
def myf(paramList):
    x = paramList[0]
    y = paramList[1]
    obs1 = x + y
    obs2 = x * x + 2 * y * y
    obsList = np.array([obs1,obs2])
    return obsList

In [3]:
# Prepare the three inputs necessary for the forecasting tool:
# observable function, fiducial parameter values, and observable covariance matrix.
observables = myf
fiducial_values = [1, 2]
covmat = np.array([[1,0],[0,1]])

In [4]:
# Initialize the forecasting utility using these inputs.
forecaster = ForecastKit(observables, fiducial_values, covmat)

In [5]:
# Compute and print all first-order derivatives of the observables.
first_order_derivs = forecaster.get_derivatives(derivative_order = 1)
print(first_order_derivs)

[[1. 2.]
 [1. 8.]]


In [6]:
# Compute and print all second-order derivatives of the observables.
second_order_derivs = forecaster.get_derivatives(derivative_order = 2)
print(second_order_derivs)

[[[2.31187391e-10 2.00000000e+00]
  [1.37983094e-13 1.39672683e-13]]

 [[4.28029189e-14 6.21768717e-13]
  [5.77968479e-11 4.00000000e+00]]]


In [7]:
# Compute and print the Fisher matrix.
fisher_matrix = forecaster.get_forecast_tensors(forecast_order = 1)
print('Fisher matrix: ')
print(fisher_matrix.ndim)
print(fisher_matrix)

Fisher matrix: 
2
[[ 5. 17.]
 [17. 65.]]


In [8]:
# Compute and print the DALI "G" and "H" tensors of the doublet-DALI approximation.
DALI_G, DALI_H = forecaster.get_forecast_tensors(forecast_order = 2)
print('G tensor: ')
print(DALI_G.ndim)
print(DALI_G)
print('H tensor: ')
print(DALI_H.ndim)
print(DALI_H)

G tensor: 
3
[[[4.00000000e+00 1.60000000e+01]
  [4.17328459e-13 1.25536456e-12]]

 [[1.28634035e-12 5.01695265e-12]
  [8.00000000e+00 3.20000000e+01]]]
H tensor: 
4
[[[[4.00000000e+00 2.79345366e-13]
   [1.24353743e-12 8.00000000e+00]]

  [[2.79345366e-13 3.85477925e-26]
   [9.27501839e-26 5.58690731e-13]]]


 [[[1.24353743e-12 9.27501839e-26]
   [3.88428427e-25 2.48707487e-12]]

  [[8.00000000e+00 5.58690731e-13]
   [2.48707487e-12 1.60000000e+01]]]]
