# Fisher and DALI demo

This demo illustrates how to use the helper tools in <code>forecast_kit</code> to facilitate scientific forecasting.

The forecasting tools can return a Fisher matrix, and the 3-dimensional and 4-dimensional tensors of the doublet-DALI approximation.

The required inputs are:
- **A function defining your observable(s):** This should take as input a single list of parameter values, corresponding to your model parameters. It should return a list of observables. A one-parameter model, or a single observable, should still be structured as a list containing one item.
- **The fiducial values of your model parameter(s):** This should likewise be a single list of parameter values. The ordering of the parameters should match the input of your observable function.
- **The covariance matrix of the observable(s):** The ordering of the entries in the covariance matrix should match the output of your observable function.

In [1]:
import numpy as np
from derivkit.forecast_kit import ForecastKit

In [2]:
# Define a function: it returns two observables as a function of two model parameters.
def myf(paramList):
    x = paramList[0]
    y = paramList[1]
    obs1 = x + y
    obs2 = x * x + 2 * y * y
    obsList = np.array([obs1,obs2])
    return obsList

In [3]:
# Prepare the three inputs necessary for the forecasting tool:
# observable function, fiducial parameter values, and observable covariance matrix.
observables = myf
fiducial_values = [1, 2]
covmat = np.array([[1,0],[0,1]])

In [4]:
# Initialize the forecasting utility using these inputs.
forecaster = ForecastKit(observables, fiducial_values, covmat)

In [5]:
# Compute and print all first-order derivatives of the observables.
first_order_derivs = forecaster.get_derivatives(derivative_order = 1)
print(first_order_derivs)

/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.324 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.0879 vs tol 0.05).
  warnings.warn(


[[ 58.33333333  58.33333333]
 [ 58.33333333 350.        ]]


/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.324 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 1.29 vs tol 0.05).
  warnings.warn(


In [6]:
# Compute and print all second-order derivatives of the observables.
second_order_derivs = forecaster.get_derivatives(derivative_order = 2)
print(second_order_derivs)

/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.352 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.088 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.647 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56

[[[-1.25000000e+04 -1.25000000e+04]
  [ 1.36969341e-12  1.11738146e-12]]

 [[ 2.73938681e-12  1.78781034e-11]
  [-1.25000000e+04 -7.50000000e+04]]]


/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.352 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 1.41 vs tol 0.05).
  warnings.warn(


In [7]:
# Compute and print the Fisher matrix.
fisher_matrix = forecaster.get_forecast_tensors(forecast_order = 1)
print('Fisher matrix: ')
print(fisher_matrix.ndim)
print(fisher_matrix)

/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.324 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.0879 vs tol 0.05).
  warnings.warn(


Fisher matrix: 
2
[[  6805.55555556  23819.44444444]
 [ 23819.44444444 125902.77777778]]


/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.324 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 1.29 vs tol 0.05).
  warnings.warn(


In [8]:
# Compute and print the DALI "G" and "H" tensors of the doublet-DALI approximation.
DALI_G, DALI_H = forecaster.get_forecast_tensors(forecast_order = 2)
print('G tensor: ')
print(DALI_G.ndim)
print(DALI_G)
print('H tensor: ')
print(DALI_H.ndim)
print(DALI_H)

/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.324 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.0879 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adapt

G tensor: 
3
[[[-1.45833333e+06 -5.10416667e+06]
  [ 1.45079367e-10  4.70982294e-10]]

 [[ 1.20268693e-09  6.41713375e-09]
  [-5.10416667e+06 -2.69791667e+07]]]
H tensor: 
4
[[[[ 3.12500000e+08 -3.10884358e-08]
   [-2.57718628e-07  1.09375000e+09]]

  [[-3.10884358e-08  3.12460136e-24]
   [ 2.37287814e-23 -1.00924777e-07]]]


 [[[-2.57718628e-07  2.37287814e-23]
   [ 3.27130821e-22 -1.37510009e-06]]

  [[ 1.09375000e+09 -1.00924777e-07]
   [-1.37510009e-06  5.78125000e+09]]]]


/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:514: RuntimeWarning: Falling back to finite difference derivative.
  warnings.warn("Falling back to finite difference derivative.", RuntimeWarning)
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 0.352 vs tol 0.05).
  warnings.warn(
/hpc/group/cosmology/blc56/Soft/derivkit/src/derivkit/adaptive_fit.py:247: RuntimeWarning: [AdaptiveFitDerivative] Falling back to finite differences because polynomial fit did not meet tolerance (last max residual 1.41 vs tol 0.05).
  warnings.warn(
